"""Default role template seeds.

Only 2 examples — businesses create their own via the UI.
"""
from __future__ import annotations

DEFAULT_TEMPLATES: list[dict] = [
    {
        "slug": "warehouse_operator",
        "name": "Almacenista",
        "description": "Operador de piso: recibe, despacha y transfiere stock",
        "icon": "warehouse",
        "permissions": [
            "products.view",
            "warehouses.view",
            "stock.view",
            "stock.receive",
            "stock.issue",
            "stock.transfer",
            "stock.return",
            "stock.waste",
            "movements.view",
            "batches.view",
            "batches.manage",
            "serials.view",
            "serials.manage",
            "cycle_counts.view",
            "cycle_counts.execute",
        ],
    },
    {
        "slug": "supervisor",
        "name": "Supervisor",
        "description": "Supervisa todas las operaciones, aprueba, pero no elimina ni configura",
        "icon": "eye",
        "permissions": [
            "products.view",
            "warehouses.view",
            "stock.view",
            "movements.view",
            "suppliers.view",
            "purchase_orders.view",
            "production.view",
            "recipes.view",
            "batches.view",
            "serials.view",
            "cycle_counts.view",
            "events.view",
            "reports.view",
            "products.create",
            "products.edit",
            "products.import",
            "warehouses.create",
            "warehouses.edit",
            "stock.receive",
            "stock.issue",
            "stock.transfer",
            "stock.adjust",
            "stock.return",
            "stock.waste",
            "suppliers.create",
            "suppliers.edit",
            "purchase_orders.create",
            "purchase_orders.edit",
            "purchase_orders.approve",
            "purchase_orders.receive",
            "production.create",
            "production.execute",
            "production.approve",
            "recipes.create",
            "batches.manage",
            "serials.manage",
            "cycle_counts.create",
            "cycle_counts.execute",
            "cycle_counts.approve",
            "events.create",
            "events.manage",
            "reports.download",
        ],
    },
]
